---
- hosts: all
  sudo: yes
  tasks:
    - name: Check for presence of packages and install if missing
      apt: pkg={{ item }} state=present
      with_items:
        - python-lxml

    - name: Run test script against VRK TestService
      script: files/kapa-testapp.py -i {{ sdsb_instance }} -l {{ member_class }} -c {{ member_code }} -s {{ subsystem_code }} -t {{ target_url }} -g {{ ansible_ssh_user }}
      register: result

    - name: Fail if result not found
      command: /bin/false
      when: result.stdout.find('Hello ''{{ ansible_ssh_user }}''') == -1
